Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'


Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'test.ruby'

Metrics/AbcSize:
  Max: 161

Metrics/BlockLength:
  Max: 173

Metrics/ClassLength:
  Max: 352

Metrics/CyclomaticComplexity:
  Max: 31

Metrics/MethodLength:
  Max: 99

Metrics/ModuleLength:
  Max: 200

Metrics/PerceivedComplexity:
  Max: 31

Naming/PredicateName:
  Exclude:
    - 'spec/**/*'

Naming/UncommunicativeMethodParamName:
  Exclude:
    - 'app/helpers/application_helper.rb'
    - 'test.ruby'

Naming/VariableName:
  Exclude:

Security/Eval:
  Exclude:

Style/AsciiComments:
  Exclude:

Style/ClassAndModuleChildren:
  Exclude:

Style/DateTime:
  Exclude:
    - 'test.ruby'

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IdenticalConditionalBranches:
  Exclude:

Style/IfInsideElse:
  Exclude:

Style/Lambda:
  Exclude:

Style/MutableConstant:
  Exclude:

Style/NumericLiterals:
  MinDigits: 6

Style/NumericPredicate:
  Exclude:
    - 'spec/**/*'

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Exclude:

Style/WordArray:
  Exclude:

Metrics/LineLength:
  Max: 416

