default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: smart_promo_api_development
  port: 5440
  user: postgres
  password: password

test:
  <<: *default
  database: smart_promo_api_test
  port: 5440
  user: postgres
  password: password

production:
  <<: *default
  database: smart_promo_api_production
  username: smart_promo_api
  password: <%= ENV['SMART_PROMO_API_DATABASE_PASSWORD'] %>
